### ISSUE TITLE
error in running

### ISSUE THREAD

**Issue by Nabeel-javed** [solidquant/sandooo#2]
cloned your project and used `cargo run` but facing this error

noteL i've updated HTTP_URL, WSS_URL and private key in the .env file
![image](https://github.com/solidquant/sandooo/assets/95472385/066baa82-cb4d-4568-ac72-7df9e6346853)

**Comment by solidquant** [comment]
Hey there you need to create an empty directory called "cache" in the root directory to resolve this issue. I'll update it so we can do a check and if it doesn't exist, make it automatically create the directory
